<?php

namespace app\home\controller;

use app\common\model\Cargo;
use app\common\model\Category;
use app\common\model\Goods;
use think\Controller;
use think\Request;
use think\Session;

class Entry extends Controller
{
    protected $categoryData;
    protected $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $model = new Category();
        $this->categoryData = $model->where('pid',0)->select();
        //halt($this->cateData);
        $this->model = $model;
    }

    /**
     * 前台首页
     *
     * @return \think\Response
     */
    public function index()
    {
//        $cateData = $this->categoryData;
        $categoryData = Category::all();
        $categoryData = \houdunwang\arr\Arr::tree($categoryData,'name','id','pid');
        //$cargoData = Cargo::all();
        $goodsData = Goods::where('cate_id',1)->select();
        $goodsData1 = Goods::where('cate_id',2)->select();
        $goodsData2 = Goods::where('cate_id',3)->select();
        //halt($goodsData);
        return view('',compact('categoryData','goodsData','goodsData1','goodsData2'));
    }

    /**
     * 列表页
     *
     * @return \think\Response
     */
    public function lists()
    {

        // 获取路由参数
        $cid = input('id');
        //halt($cid);
        // 分类数据
        $categoryData = Category::all();
        //栏目名称
        $title = Category::get($cid)['name'];
        //p($title);exit;
        $categoryData = \houdunwang\arr\Arr::tree($categoryData,'name','id','pid');
        //halt($categoryData);
        // 获取该顶级分类 以及其全部分类
        $pcategoryData = $this->model->get($cid);
        //halt($pcategoryData);
        // 分类的父级id  pid
        $pid = $pcategoryData['pid'];
        //halt($pid) 0;
        // 获取 子类
        $subCategoryData = $this->model->where('pid',$cid)->select();
        //halt($subCategoryData);
        if(!$subCategoryData && $pid !=0){

            // 当是访问文件分类时，取出他的pid
            $subCategoryData = $this->model->where('pid',$pid)->select();
            // 获取单个子类数据
            $goodsData = Goods::where('pid',$cid)->field('id,gname,price,click,content')->select();


        }else{
            // 获取全部商品数据
            //$subData = $this->model->where('pid',0)->column('id');
            //halt($subData);
            $goodsData = Goods::where('cate_id',$cid)->select();
            //halt($goodsData);
        }

        // 取出商品数据
        // 1. 当商品是全部时 首先获取子分类 再取出数据
        // 当时子分类时 直接取出数据
        //halt($goodsData);
        return view('',compact('categoryData','pcategoryData','subCategoryData','pid','goodsData','title'));
    }


    /**
     * 内容页
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function content()
    {
        $gid = input('id');
        //栏目数据
        $categoryData = Category::all();
        $categoryData = \houdunwang\arr\Arr::tree($categoryData,'name','id','pid');

        //商品数据
        $goodsData = Goods::where('id',$gid)->select();

        //最爱排行
        $lovegoodsData = Goods::limit(3,11)->select();
        //halt($lovegoodsData);
        //热销排行
        $hotgoodsData = Goods::limit(10,5)->select();
        //halt($hotgoodsData);
        //$goodsData = $this->model->get($gid);
        //halt($goodsData);
        //货品属性数据
        $cargoData = Cargo::where('goods_id',$gid)->select();
        //halt($cargoData);
        $totalNum = 0;
        foreach ($cargoData as $v){
            $totalNum += $v['total'];
        }
        //$a = $cargoData[1]['attribute'];
        //halt($a);
//        $cargoData = json_encode($cargoData,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
//        halt($cargoData);
        //$cargoData = explode(',',$cargoData);
        //halt($cargoData);

        // 获取商品图集
        //$images = $goodsData['pics'];
        //halt($images);
        //$images = explode('|',$images);

        // 获取后台分类顶级分类表数据
        // select 选择数据集
//        $this->model = new Goods();
//        $categoryData = $this->categoryData;
        //halt($categoryData);

        //购物车数据
        $goods = Session::get('cart.goods');
        $cart = json_encode($goods,JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        return view('',compact('categoryData','goodsData','cargoData','totalNum','cart','lovegoodsData','hotgoodsData'));
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
