<?php

namespace app\home\controller;

use app\common\model\Cargo;
use app\common\model\Category;
use app\common\model\Flows;
use app\common\model\Goods;
use houdunwang\arr\Arr;
use think\Controller;
use think\Request;
use think\Session;

class Flow extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!Session::get('user_id')){
            $this->error('请先登录','/login.html');
        }
    }

    /**
     * 结算、提交订单
     *
     * @return \think\Response
     */
    public function index()
    {
        //商品信息
        $data = Session::get('cart');
        //halt($data);
        //地址栏信息
        if (IS_POST){
            $model = new Flows();
            $model->order_name = Session::get('user_name').time();
            $model->provinces = input('post.province');
            $model->city = input('post.city');
            $model->district = input('post.district');
            $model->zipcode = input('post.zipcode');
            $model->address = input('post.address');
            $model->addrName = input('post.addrName');
            $model->mobile = input('post.mobile');
            $model->user_id = Session::get('user_id');
            $model->status = '未发货';
            //halt($model->user_id);
            $model->total = $data['total'];
            $model->goods_info = json_encode($data,JSON_UNESCAPED_UNICODE,JSON_UNESCAPED_SLASHES);
            $res = $model->save();
            if ($res){
                //商品表中想要数据减少
                $goodsModel = new Cargo();
                foreach ($data['goods'] as $k=>$v){
                    $num = $v['total']-$v['total'];
                    Cargo::where('id',$v['id'])->update(['total'=>$num]);
                }
                //清空购物车
                Session::delete('cart');
                $this->success('购买成功','/home/Flow/lists');
            }else{
                $this->error('购买成功');
            }
        }
        //栏目信息
        $categoryData = Category::all();
        $categoryData = Arr::tree($categoryData,'name','id','pid');

        //halt($data);
        //将商品信息添加
        if (!is_null($data['goods'])){
            foreach ($data['goods'] as $k=>$v){
                $info = Goods::get($v['id'])->toArray();
                $data[$k]['info'] = $info;
            }
        }
        //$data = json_encode($data,JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        //halt($data);
        return view('',compact('categoryData','data','$model->mobile'));
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
